from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Type

import numpy as np

from xsynth.signal import SignalGenerator, ADAPTSignalGenerator
from xsynth.device import ADAPTX, ADAPT_MLS, IBFB_X, IBFB_Y


def get_oscillator_registry() -> Dict[str, Type]:
    dummy_t = np.arange(0, 10)
    generator = SignalGenerator(dummy_t)
    return generator.__base__


def get_oscillator_names() -> list[str]:
    return list(get_oscillator_registry().keys())


@dataclass
class AdaptSlot:
    device_name: str = "ADAPTX"
    beam_region: str = "SA3"
    oscillator_name: str = "line"
    generator: ADAPTSignalGenerator | None = None
    server: object | None = None

    def connect(self) -> None:
        if self.device_name == "ADAPTX":
            self.server = ADAPTX(beam_region=self.beam_region)
        elif self.device_name == 'ADAPT_MLS':
            self.server = ADAPT_MLS(beam_region=self.beam_region)
        elif self.device_name == 'IBFB_X': 
            self.server = IBFB_X(beam_region=self.beam_region)
        elif self.device_name == 'IBFB_Y': 
            self.server = IBFB_Y(beam_region=self.beam_region)
        else:
            raise ValueError(f"Unsupported ADAPT device: {self.device_name}")

        self.generator = ADAPTSignalGenerator(
            adaptation_server=self.server,
            oscillator=self.oscillator_name,
        )

    @property
    def variables(self) -> dict:
        if self.generator is None:
            return {}
        return self.generator.variables

    @property
    def signal_params(self) -> dict:
        if self.generator is None:
            return {}
        return self.generator.signal_params

    @property
    def t(self):
        if self.generator is None:
            return np.arange(0, 1)

        return np.asarray(self.generator.t)

    @property
    def preview_signal(self):
        """Signal currently generated by the GUI oscillator."""
        if self.generator is None:
            return np.zeros(1)

        return np.asarray(self.generator.signal)

    @property
    def read_signal(self):
        """Signal currently read back from the adaptation server."""
        if self.server is None:
            return np.zeros(1)

        return np.asarray(self.server.read())

    def set_oscillator(self, oscillator_name: str, **kwargs) -> None:
        self.oscillator_name = oscillator_name

        if self.generator is not None:
            self.generator.set_oscillator(oscillator_name, **kwargs)

    def update_variable(self, name: str, value: float) -> None:
        if self.generator is None:
            raise RuntimeError("ADAPT slot is not connected.")

        self.generator.update_variable(**{name: value})

    def write(self) -> None:
        if self.generator is None:
            raise RuntimeError("ADAPT slot is not connected.")

        self.generator.write()
